In [9]:
import pandas as pd
data={"Name":["Alex","Rahul","Raju","Rajesh"],
      "Age":[23,25,28,24],
      "City":["Mumbai","Hyderabad","Jaipur","Banglore"]}
details=pd.DataFrame(data)
print(details)

     Name  Age       City
0    Alex   23     Mumbai
1   Rahul   25  Hyderabad
2    Raju   28     Jaipur
3  Rajesh   24   Banglore

In [10]:
#SHAPE METHOD TO KNOW SIZE TABLE 
print(details.shape)

(4, 3)

In [11]:
#details of columns
print(details.columns)

Index(['Name', 'Age', 'City'], dtype='object')

In [12]:
print(details.index)

RangeIndex(start=0, stop=4, step=1)

In [13]:
print(details.head())  #to view the data of record(top 5)

     Name  Age       City
0    Alex   23     Mumbai
1   Rahul   25  Hyderabad
2    Raju   28     Jaipur
3  Rajesh   24   Banglore

In [14]:
print(details.tail())   #show last five records

     Name  Age       City
0    Alex   23     Mumbai
1   Rahul   25  Hyderabad
2    Raju   28     Jaipur
3  Rajesh   24   Banglore

In [53]:
print(details.sample(2))   #show any random record of numbers which we are giving

    Name  Age       City
1  Rahul   25  Hyderabad
0   Alex   23     Mumbai

In [15]:
print(details.info()) #all info of the table

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    4 non-null      object
 1   Age     4 non-null      int64
 2   City    4 non-null      object
dtypes: int64(1), object(2)
memory usage: 228.0+ bytes
None

In [55]:
print(details.describe())  #details of table

             Age
count   4.000000
mean   25.000000
std     2.160247
min    23.000000
25%    23.750000
50%    24.500000
75%    25.750000
max    28.000000

In [16]:
print(details[["Name","Age"]]) #show the column we want

     Name  Age
0    Alex   23
1   Rahul   25
2    Raju   28
3  Rajesh   24

In [17]:
print(details.loc[0])   #show the details of record in a particular row

Name      Alex
Age         23
City    Mumbai
Name: 0, dtype: object

In [18]:
print(details.loc[[0,2]])   #show multiple records in rows

   Name  Age    City
0  Alex   23  Mumbai
2  Raju   28  Jaipur

In [26]:
print(details.iloc[0]) #access using position

Name      Alex
Age         23
City    Mumbai
Name: 0, dtype: object

In [ ]:
#FILTERING DATA

In [19]:
print (details[details.Age>23])

     Name  Age       City
1   Rahul   25  Hyderabad
2    Raju   28     Jaipur
3  Rajesh   24   Banglore

In [60]:
print(details[details.Age>23],[details.Age<25])

     Name  Age       City
1   Rahul   25  Hyderabad
2    Raju   28     Jaipur
3  Rajesh   24   Banglore [0     True
1    False
2    False
3     True
Name: Age, dtype: bool]

In [20]:
details["Grade"]='A','B','C','D'
print(details)

     Name  Age       City Grade
0    Alex   23     Mumbai     A
1   Rahul   25  Hyderabad     B
2    Raju   28     Jaipur     C
3  Rajesh   24   Banglore     D

In [21]:
details["Age"]=details["Age"]+2
print(details)

     Name  Age       City Grade
0    Alex   25     Mumbai     A
1   Rahul   27  Hyderabad     B
2    Raju   30     Jaipur     C
3  Rajesh   26   Banglore     D

In [22]:
students=pd.DataFrame({
    "ID":[12,13,14,15],
    "Name":["Max","Rahul","Abdul","Rimsha"]})
print(students)

   ID    Name
0  12     Max
1  13   Rahul
2  14   Abdul
3  15  Rimsha

In [23]:
students2=pd.DataFrame({
    "ID":[12,13,14,15],                       
    "Marks":[70,80,90,78]})
print(students2)

   ID  Marks
0  12     70
1  13     80
2  14     90
3  15     78

In [77]:
students=pd.DataFrame({
    "ID":[12,13,14,15],
    "Name":["Max","Rahul","Abdul","Rimsha"]})
students2=pd.DataFrame({
    "ID":[12,13,14,15],                       #MERGING OF TWO DATA TABLES
    "Marks":[70,80,90,78]})
result=pd.merge(students,students2,on="ID")
print(result)

   ID    Name  Marks
0  12     Max     70
1  13   Rahul     80
2  14   Abdul     90
3  15  Rimsha     78

In [90]:
pd.merge(students,students2,how="inner",on="ID")

   ID    Name  Marks
0  12     Max     70
1  13   Rahul     80
2  14   Abdul     90
3  15  Rimsha     78

In [4]:
students=pd.DataFrame({
    "ID":[12,13,14,15],
    "Name":["Max","Rahul","Abdul","Rimsha"]})
students2=pd.DataFrame({
    "ID":[12,13,14,15],                       #MERGING OF TWO DATA TABLES
    "Marks":[70,80,90,78]})
result=pd.merge(students,students2,on="ID")
print(result)

   ID    Name  Marks
0  12     Max     70
1  13   Rahul     80
2  14   Abdul     90
3  15  Rimsha     78

In [6]:
pd.merge(students,students2,how="right",on="ID")

   ID    Name  Marks
0  12     Max     70
1  13   Rahul     80
2  14   Abdul     90
3  15  Rimsha     78

In [24]:
data={"Name":["Alex","Rahul","Raju","Rajesh"],
      "Age":[23,25,28,24],
      "City":["Mumbai","Hyderabad","Jaipur","Banglore"]}
details["Grade"]='A','B','C','D'
details=pd.DataFrame(data)
print(details)

     Name  Age       City
0    Alex   23     Mumbai
1   Rahul   25  Hyderabad
2    Raju   28     Jaipur
3  Rajesh   24   Banglore